[phases.setup]
nixPkgs = ["nodejs_22"]
aptPkgs = []

[phases.install]
dependsOn = ["setup"]
cmds = [
  "cd backend/tg_bot",
  "npm install --production"
]

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'No build needed for bot'"]

[start]
cmd = "cd backend/tg_bot && npm start"

